config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  resources :comments
  
  resources :roles

  devise_for :users,
    controllers: { 
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
    }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :authorize_user!, only: %i[edit update destroy]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show  
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments or /comments.json
  def create
    #@comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id]) # Obtiene el post relacionado al comentario
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id # Asigna el usuario actual

    respond_to do |format|
      if @comment.save!
        format.html { redirect_to @post, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @post = Post.find(@comment.post_id)
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to @post, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:description, :user_id, :post_id)
    end

    # autorizamos a la edicion o eliminacion de los comments
    def authorize_user!
      unless @comment.user_id == current_user.id || current_user.role.role == "admin"
        redirect_to comments_path, alert: "Not permission to do that"
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Description:</strong>
    <%= comment.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :fullname, prompt: 'Select an user' %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.collection_select :post_id, Post.all, :id, :headline, prompt: 'Select a post' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>