config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  resources :comments
  
  resources :roles

  devise_for :users,
    controllers: { 
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
    }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <div class="container">
        <%= link_to "TheRialNews", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <%= link_to "All news",  posts_path, class:"nav-link"%>
                </li>
            </ul>
            <div class="d-flex me-0">
                <ul class="navbar-nav">
                <% if user_signed_in? %>
                <!-- User menu -->
                    <li class="nav-item">
                        <%= link_to "New Post",  new_post_path, class:"btn btn-success p-1"%>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">    
                            <%=  current_user.email %>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item disabled" href="#">Role:  <%= current_user.role.role %></a>

                            <a class="dropdown-item disabled" href="#">My Profile</a>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class:"btn btn-outline-primary d-flex" %>                        </div>
                    </li>
                <!-- // User menu -->
                <%else%>
                    <li class="nav-item">
                        <%= link_to "Sign In", new_user_session_path, class:"btn btn-outline-primary"%>
                    </li>
                <%end%>
                </ul>
            </div>
        </div>
    </div>
</nav>