config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  resources :comments
  
  resources :roles

  devise_for :users,
    controllers: { 
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
    }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 

=begin
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy 
=end

    has_many :comments, dependent: :destroy
    
    validates :headline, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show]
  before_action :authorize_user!, only: %i[edit update destroy]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:headline, :drophead, :body, :user_id)
    end

    def authorize_user!
      unless @post.user_id == current_user.id || current_user.role.role == "admin"
        redirect_to posts_path, notice: "Not permission to do that"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :headline, class:"form-label"%>
    <%= form.text_field :headline, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :drophead,  class:"form-label" %>
    <%= form.text_field :drophead, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body,  class:"form-label"%>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit class:"btn btn-success"%>
    <%= link_to "Cancel", :back, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/posts/_new_comment_form.html.erb
<%= form_with(model: [post, post.comments.build]) do |form| %>
<%
=begin%>

  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




<%
=end%>
  <div class="mb-3">
  
    <%= form.label :description, "Add a comment",
      class: "form-label"
    %>
    
    <%= form.text_field :description, 
      class: "form-control"
    %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary"
    %>
  </div>

<%end%>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Headline:</strong>
    <%= post.headline %>
  </p>

  <p>
    <strong>Drophead:</strong>
    <%= post.drophead %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/_single_post.html.erb
    <div class="card" id="<%= dom_id post %>" >
        <div class="card-header">
            <h4 class="card-title display-6">
                <%= post.headline %>
            </h4>
            <h6 class=" fs-6 card-subtitle mb-2 text-muted">
                <%= post.drophead %>
            </h6>
        </div>

        <div class="card-body">
            <p class="card-text">
                <%= post.body %>
            </p>
        </div>

        <div class="card-footer">
            <div class="d-flex justify-content-center gap-2">
                <small class="text-muted">
                    Posted by <%= post.user.email  %>
                </small>
                <small class="text-muted ">
                    <%= post.created_at.strftime("%B %d, %Y ")  %>
                </small>
            </div>
            <% if user_signed_in? %>
                
            <% if post.user_id == current_user.id || current_user.role.role == "admin" %>
                <div class="d-flex justify-content-center gap-2">
                    <%= link_to edit_post_path(post), class:"btn btn-warning p-1" do %>
                        <i class="bi bi-pencil-fill text-smaller m-0"></i>
                    <%end%>
                    <%= link_to post_path(post), class:"btn btn-success p-1" do %>
                        <i class="bi bi-chat-dots-fill text-smaller m-0"></i>
                    <%end%>
                    <%= button_to post,  method: :delete , class:"btn btn-danger p-1", 
                        turbo_data: { confirm: "Are you sure you want to delete this post?" } do %>
                        <i class="bi bi-trash-fill text-smaller m-0"></i>
                    <% end %>
                </div>
            <%end%>
        <% end %>

        </div>
    </div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1 class="display-3 text-center">Editing new <%= @post.headline%></h1>

<section class="d-flex justify-content-center">
  <%= render "form", post: @post %>
</section>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "News" %>

<section id="posts" class="d-flex justify-content-center gap-3 flex-wrap">
  <% @posts.each do |post| %>
  <div class="col-12 col-md-4">
    <%= link_to post_path(post), class: "text-decoration-none text-dark" do %>
      <%= render "single_post", post: post%>
    <%end%>
  </div> 
  <% end %>
</section>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1 class="display-3 text-center">Post your new</h1>

<section class="d-flex justify-content-center">
  <%= render "form", post: @post %>
</section>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<section class="container">
  <div class="col-12 col-md-6 mx-auto">
    <%= render "single_post", post: @post %>
  </div>
</section>

<section class="container my-5">
  <div class="col-12 col-md-6 mx-auto">
    <%= render "new_comment_form", post: @post %>
  </div>
</section>

<%
=begin%>


<% @comments.each do |comment| %>
  <% if comment.user.present? %>
    <p>User ID: <%= comment.user.id %></p>
    <%= current_user if user_signed_in? %>
  <% else %>
    <p>No user associated with this comment.</p>
  <% end %>
<% end %>



<%
=end%>


<section class="container justify-content-center">
  <h2 class="display-6 text-center">  
    <% if @comments.present? %>
      More comments
    <% else %>
      No comments associated
    <% end %>
  </h2>
  
  <% if @comments.present? %> 
    <% @comments.each do |comment| %>
      <div class="col-12 col-md-6 mx-auto">
        <div class="card mt-3">
          <p>
            <strong><%= comment.user.email %></strong> - 
            <%= comment.created_at.strftime("%B %d, %Y at %H:%M") %>
          </p>
          <p>
            <%= comment.description %>
          </p>
          <% if user_signed_in? && ( current_user.id == comment.user_id || current_user.role.role == "admin" )%>
          <div class="d-flex justify-content-center gap-2">
            <%= button_to comment, method: :delete, class: "btn btn-danger p-1", turbo_data: { confirm: "Are you sure you want to delete this post?" } do %>
                <i class="bi bi-trash-fill text-smaller m-0"></i>
            <% end %>
          </div>
          <% end %>
        </div>

      </div>
    <% end %>
    <% end %>

</section>